Fix addGitLabMRComment
jenkinsci/gitlab-plugin pull request #1364
Opened 2022-11-23 08:10 UTC by Alceatraz

Recommit of #1315, Old one is too old to merge.

2022-11-23 20:10 UTC, MarkEWaite requested changes
Most maintainers (like me) are unlikely to merge a pull request that adds functionality and includes no test of the added functionality.  When new functionality is added without a test, that places responsibility on the maintainer to verify the code is still functioning before each release.  That quickly becomes more than a maintainer can do.

Can you add one or more tests that cover the newly added code?

2022-11-24 00:21 UTC, Alceatraz commented
> Most maintainers (like me) are unlikely to merge a pull request that adds functionality and includes no test of the added functionality. When new functionality is added without a test, that places responsibility on the maintainer to verify the code is still functioning before each release. That quickly becomes more than a maintainer can do.
> 
> Can you add one or more tests that cover the newly added code?

I can understand but that become a problem for me, I do test and infact using this fork in production. But I have no idea how to write pipeline and create gitlab repo in an junit case.
I do willing provide *things* if you need, Is there any other way to prove this patch working ?

2023-01-31 00:46 UTC, krisstern commented
Hi @Alceatraz Could you add the test(s) needed for this PR if possible? Otherwise this cannot be reviewed.

2023-01-31 01:06 UTC, Alceatraz commented
> Hi @Alceatraz Could you add the test(s) needed for this PR if possible? Otherwise this cannot be reviewed.

I can't.

This feature need at least two nested jenkins pipeline and gitlab setting, Which can't set up by junit process. In my real usage, Jenkins nest depth is 4, Each of them need Add "compile success" comment into gitlab pipeline. ( Because the PR for "approve PR" is pending for 3 years now )

I can provied screenshot. But that seem like unacceptable when last time Mark asking me for tests. If so, Just close this PR. Sorry I can't help.

2023-01-31 12:13 UTC, krisstern commented
@Alceatraz No worries, now I see your pain point for adding tests. Please do provide the screenshot for me so I can check before considering merging this PR. 

Thanks very much for your contribution!

2023-01-31 13:46 UTC, krisstern commented
@MarkEWaite Is it okay for me to make an exception for adding test if after reviewing further I find the PR acceptable?

2023-03-07 14:49 UTC, MarkEWaite commented
> @MarkEWaite Is it okay for me to make an exception for adding test if after reviewing further I find the PR acceptable?

Yes.  If it has been tested interactively and you're confident in the interactive testing, then merge without tests is a reasonable exception.  We want to be careful to not use that exception too frequently or we'll get into the situation we have with the git plugin that it needs interactive testing each time it is released.

2023-03-08 06:26 UTC, Alceatraz commented
Ok, So sorry for the delay. Because the gitlab seems like brokened in recent version. Jenkins integration can't enable even with brand new install. Still fixing this issue. May be someone encounter this behavier before?

2023-03-08 07:02 UTC, Alceatraz commented
Sorry for the long time delay.

I make a non-cut screen recording video to prove the patch is valid https://youtu.be/KtTkYgeihwY

And here is the key step

```groovy
pipeline {
    agent any
    stages {
        stage('test') {
            steps {
                addGitLabMRComment(comment: 'Parent Run')
                build('slave')
                addGitLabMRComment(comment: 'Parent Done')
            }
        }
    }
}
```

```groovy
pipeline {
    agent any
    stages {
        stage('test') {
            steps {
                addGitLabMRComment(comment: 'Slave Working')
            }
        }
    }
}
```


Using origin plugin:

![1](https://user-images.githubusercontent.com/8266702/223641676-65ce4034-bc7c-435b-98e2-eecd4c395dbd.jpg)


Replace with my patched plugin:

![2](https://user-images.githubusercontent.com/8266702/223641736-737b6f57-0ae6-4b89-9851-5f8081ccb632.jpg)

2023-03-08 07:03 UTC, Alceatraz commented
BTW: I will delete the youtube video when this PR merged.

2023-03-15 14:04 UTC, krisstern commented
Thanks @Alceatraz for the follow-up! Let me test it and review this pull request soon

2023-03-15 14:05 UTC, krisstern commented
> > @MarkEWaite Is it okay for me to make an exception for adding test if after reviewing further I find the PR acceptable?
> 
> Yes. If it has been tested interactively and you're confident in the interactive testing, then merge without tests is a reasonable exception. We want to be careful to not use that exception too frequently or we'll get into the situation we have with the git plugin that it needs interactive testing each time it is released.

Thanks @MarkEWaite

2023-03-29 13:55 UTC, krisstern requested changes
Some editing requested, otherwise looks good!

2023-03-29 13:55 UTC, krisstern commented on src/main/java/com/dabsquared/gitlabjenkins/workflow/AddGitLabMergeRequestCommentStep.java
> +            // @ Alceatraz Warprays BEGIN
```suggestion
```

2023-03-29 13:55 UTC, krisstern commented on src/main/java/com/dabsquared/gitlabjenkins/workflow/AddGitLabMergeRequestCommentStep.java
> +            // @ Alceatraz Warprays END
```suggestion
```

2023-03-29 13:55 UTC, krisstern commented on src/main/java/com/dabsquared/gitlabjenkins/workflow/AddGitLabMergeRequestCommentStep.java
> +            // @ Alceatraz Warprays BEGIN
```suggestion
```

2023-03-29 13:55 UTC, krisstern commented on src/main/java/com/dabsquared/gitlabjenkins/workflow/AddGitLabMergeRequestCommentStep.java
> +            // @ Alceatraz Warprays END
```suggestion
```

2023-03-29 13:55 UTC, krisstern commented on src/main/java/com/dabsquared/gitlabjenkins/workflow/AddGitLabMergeRequestCommentStep.java
> +                                                                       causes) {
```suggestion
    private static List<GitLabWebHookCause> retrieveCauseRecursive(List<Cause> causes) {
```

2023-03-29 13:55 UTC, krisstern commented on src/main/java/com/dabsquared/gitlabjenkins/workflow/AddGitLabMergeRequestCommentStep.java
> +                  "retrieve GitLab MR context: Can't find GitLabWebHookCause");
```suggestion
                LOGGER.log(Level.WARNING, "Add MR comment failure, " +
                  "Cannot retrieve GitLab MR context: Cannot find GitLabWebHookCause");
```

2023-03-29 13:58 UTC, krisstern commented
Will merge once CI checks have all been passed.

2023-03-29 14:21 UTC, krisstern commented on src/main/java/com/dabsquared/gitlabjenkins/workflow/AddGitLabMergeRequestCommentStep.java
> +     * Notice: Only retrieve the first founded GitLabWebHookCause instance.
```suggestion
     * Notice: Only retrieve the first found GitLabWebHookCause instance.
```

2023-03-30 00:20 UTC, krisstern approved these changes
Thanks @Alceatraz

2023-03-30 00:23 UTC, krisstern commented
@MarkEWaite Is it okay to approve this pull request? I have checked that nothing seems out of place and it does what it is intended to do. But we will need your approval since you have requested changes to be made.

2023-03-30 12:49 UTC, merged