adding acceptgitlabmergerequeststeptest
jenkinsci/gitlab-plugin pull request #1434
Opened 2023-03-22 12:13 UTC by harsh-ps-2003

Adding the missing acceptgitlabmergerequeststeptest.java in the workflow folder with the required groovy script acceptgitlabmergerequest.groovy

2023-03-22 14:30 UTC, MarkEWaite requested changes

2023-03-22 14:30 UTC, MarkEWaite commented on src/test/java/com/dabsquared/gitlabjenkins/workflow/AcceptGitLabMergeRequestStepTest.java
> +
Could you remove the trailing white space from this line?
```suggestion

```

2023-03-22 14:30 UTC, MarkEWaite commented on src/test/java/com/dabsquared/gitlabjenkins/workflow/AcceptGitLabMergeRequestStepTest.java
> +
Could you also remove the trailing white space from this line?

Ultimately it would be nice to have `spotless` implemented in this plugin so that it would be automatically done each time we run the `mvn spotless:apply` .

This pull request does not need to do anything with `spotless`.  If it is done, it should be in a separate pull request.  There are implementations of `spotless` in [embeddable build status plugin](https://github.com/jenkinsci/embeddable-build-status-plugin/blob/93c2b10f79796cf9a1dbc0f638cde60f18ff78f2/pom.xml#L96), [priority sorter plugin](https://github.com/jenkinsci/priority-sorter-plugin/blob/e47e12f455c616f0afc94841946ff663e76c237d/pom.xml#L65), and in [Jenkins core](https://github.com/jenkinsci/jenkins/blob/696b286e1f9fb161c1a601ede74f9a5c1525dcce/pom.xml#L351) in case you're interesting in proposing a separate pull request that automatically removes trailing white space from the source code.
```suggestion

```

2023-03-22 14:30 UTC, MarkEWaite commented on src/test/java/com/dabsquared/gitlabjenkins/workflow/AcceptGitLabMergeRequestStepTest.java
> +                    IOUtils.toString(
I really like this technique with a separate file that is the Pipeline script.  Unfortunately, when I run the test, it reports a null pointer exception in the test.  I suspect that means that even though the test is running, it is not doing what you hoped it would do.

The stack trace that I see is:

```
[INFO] Running com.dabsquared.gitlabjenkins.workflow.AcceptGitLabMergeRequestStepTest
=== Starting acceptGitlabMergeRequest(com.dabsquared.gitlabjenkins.workflow.AcceptGitLabMergeRequestStepTest)
Will load plugins: RealJenkinsRuleInit.jpi apache-httpcomponents-client-4-api.jpi bootstrap5-api.jpi bouncycastle-api.jpi branch-api.jpi caffeine-api.jpi checks-api.jpi cloudbees-folder.jpi co                                        mmons-lang3-api.jpi commons-text-api.jpi configuration-as-code.jpi credentials-binding.jpi credentials.jpi display-url-api.jpi durable-task.jpi echarts-api.jpi font-awesome-api.jpi git-client.                                        jpi git.jpi gitlab-plugin.jpl instance-identity.jpi ionicons-api.jpi jackson2-api.jpi jakarta-activation-api.jpi jakarta-mail-api.jpi javax-activation-api.jpi jaxb.jpi jersey2-api.jpi jquery3-                                        api.jpi junit.jpi mailer.jpi matrix-auth.jpi matrix-project.jpi mina-sshd-api-common.jpi mina-sshd-api-core.jpi plain-credentials.jpi plugin-util-api.jpi popper2-api.jpi scm-api.jpi script-sec                                        urity.jpi snakeyaml-api.jpi ssh-credentials.jpi structs.jpi trilead-api.jpi workflow-api.jpi workflow-basic-steps.jpi workflow-cps.jpi workflow-durable-task-step.jpi workflow-job.jpi workflow-                                        multibranch.jpi workflow-scm-step.jpi workflow-step-api.jpi workflow-support.jpi
2023-03-22 08:24:41 5.15.0 WARNING null
java.lang.NullPointerException
        at java.base/java.io.Reader.<init>(Reader.java:167)
        at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:109)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:1021)
        at org.apache.commons.io.IOUtils.toString(IOUtils.java:2839)
        at org.apache.commons.io.IOUtils.toString(IOUtils.java:2819)
        at com.dabsquared.gitlabjenkins.workflow.AcceptGitLabMergeRequestStepTest.acceptGitlabMergeRequest(AcceptGitLabMergeRequestStepTest.java:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

2023-03-22 14:31 UTC, MarkEWaite commented
Thanks for the pull request adding more tests.  Much appreciated!

2023-03-22 20:58 UTC, MarkEWaite commented
I checkout the pull request with the command:

```
$ gh pr checkout 1434
```

I see that it contains several commits including:

* 4381f3b Update src/test/java/com/dabsquared/gitlabjenkins/workflow/AcceptGitLabMergeRequestStepTest.java
* 58269ab Update src/test/java/com/dabsquared/gitlabjenkins/workflow/AcceptGitLabMergeRequestStepTest.java
* b89791f patched NPE
* b661802 added groovy script for the test
* 5c408cc added AcceptGitLabMergeRequestStepTest

I run the tests with Apache Maven 3.9.1 and Java 11.0.18 as reported:

```
$ mvn -version
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
Maven home: /home/mwaite/tools/apache-maven-3.9.1
Java version: 11.0.18, vendor: Eclipse Adoptium, runtime: /opt/jdk-11
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-425.13.1.el8_7.x86_64", arch: "amd64", family: "unix"
```

The tests pass (maven returns a zero exit code) but the following message is displayed on the terminal where I run the tests:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.dabsquared.gitlabjenkins.workflow.AcceptGitLabMergeRequestStepTest
=== Starting acceptGitlabMergeRequest(com.dabsquared.gitlabjenkins.workflow.AcceptGitLabMergeRequestStepTest)
Will load plugins: RealJenkinsRuleInit.jpi apache-httpcomponents-client-4-api.jpi bootstrap5-api.jpi bouncycastle-api.jpi branch-api.jpi caffeine-api.jpi checks-api.jpi cloudbees-folder.jpi commons-lang3-api.jpi commons-text-api.jpi configuration-as-code.jpi credentials-binding.jpi credentials.jpi display-url-api.jpi durable-task.jpi echarts-api.jpi font-awesome-api.jpi git-client.jpi git.jpi gitlab-plugin.jpl instance-identity.jpi ionicons-api.jpi jackson2-api.jpi jakarta-activation-api.jpi jakarta-mail-api.jpi javax-activation-api.jpi jaxb.jpi jersey2-api.jpi jquery3-api.jpi junit.jpi mailer.jpi matrix-auth.jpi matrix-project.jpi mina-sshd-api-common.jpi mina-sshd-api-core.jpi plain-credentials.jpi plugin-util-api.jpi popper2-api.jpi scm-api.jpi script-security.jpi snakeyaml-api.jpi ssh-credentials.jpi structs.jpi trilead-api.jpi workflow-api.jpi workflow-basic-steps.jpi workflow-cps.jpi workflow-durable-task-step.jpi workflow-job.jpi workflow-multibranch.jpi workflow-scm-step.jpi workflow-step-api.jpi workflow-support.jpi
2023-03-22 14:53:23 5.15.0 WARNING null
java.lang.NullPointerException
        at java.base/java.io.Reader.<init>(Reader.java:167)
        at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:109)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:1021)
        at org.apache.commons.io.IOUtils.toString(IOUtils.java:2839)
        at org.apache.commons.io.IOUtils.toString(IOUtils.java:2819)
        at com.dabsquared.gitlabjenkins.workflow.AcceptGitLabMergeRequestStepTest.acceptGitlabMergeRequest(AcceptGitLabMergeRequestStepTest.java:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

I think that null pointer exception means that inside the RealJenkinsRule test the attempt to read the Pipeline script definition is failing with a null pointer exception.  I think that indicates that something unexpected is happening in the test.

One way to get rid of the null pointer exception might be to replace the IOUtils.toString() call that reads the separate file with an inline insertion of the contents of the text file into the Java source file.  I haven't tried it, but I believe that is the technique that I've used in other locations.  It is not as elegant as a separate file, but avoids the complexity of finding the file in the plugin resources.

2023-03-22 21:00 UTC, MarkEWaite requested changes
Based on the null pointer exception that is reported, I believe more changes are needed.

2023-03-23 08:06 UTC, krisstern commented on src/test/java/com/dabsquared/gitlabjenkins/workflow/AcceptGitLabMergeRequestStepTest.java
> +}
```suggestion
}

```

2023-03-23 08:07 UTC, krisstern commented on src/test/java/com/dabsquared/gitlabjenkins/workflow/AcceptGitLabMergeRequestStepTest.java
> +}
Please add a blank line to the end of the file.

2023-03-26 08:28 UTC, krisstern commented
I cannot approve this PR as it currently stands, if its purpose is to improve code coverage. If you run `mvn -P enable-jacoco clean verify` to generate an HTML visualization of the code coverage, you will find that the code coverage change is exactly `0%`:

<img width="1440" alt="Screenshot 2023-03-26 at 3 55 11 PM" src="https://user-images.githubusercontent.com/88480540/227764130-0d8ed37b-0016-4347-8572-cf8852851759.png">

<img width="1326" alt="Screenshot 2023-03-26 at 4 21 47 PM" src="https://user-images.githubusercontent.com/88480540/227764149-b2d91d1b-2aa4-4fc4-a8d2-eaf01ab8951e.png">

<img width="1381" alt="Screenshot 2023-03-26 at 4 27 19 PM" src="https://user-images.githubusercontent.com/88480540/227764202-a3cdbdd0-9257-4a62-94c1-fd9c6f079ec8.png">

2023-03-26 08:58 UTC, krisstern commented
@harsh-ps-2003 Did you copy and paste most code from https://github.com/harsh-ps-2003/gitlab-plugin/blob/3bb4fd27346f0c50f4249be5f8932da062c92d0d/src/test/java/com/dabsquared/gitlabjenkins/workflow/UpdateGitLabCommitStatusStepTest.java? I am asking because the test does not seem to be testing for accept GitLab merge request, as it does not use any methods from https://github.com/jenkinsci/gitlab-plugin/blob/2d40c64e0292e1042844bed2fd6b3f6cd6da210b/src/main/java/com/dabsquared/gitlabjenkins/workflow/AcceptGitLabMergeRequestStep.java.

2023-03-26 09:03 UTC, krisstern commented
And after double-checking, I think without this PR the `AcceptGitLabMergeRequestStep.AcceptGitLabMergeRequestStepExecution`, `AcceptGitLabMergeRequestStep`, and `AcceptGitLabMergeRequestStep.DescriptorImpl` are already covered by the existing tests.

2023-03-26 09:10 UTC, closed without merging