Improve RegexBasedFilter doc
jenkinsci/gitlab-plugin pull request #1463
Opened 2023-05-02 23:53 UTC by harsh-ps-2003

Adding missing examples and some explanation related to regular expressions used in RegexBasedFilter.

Closes #1269

2023-05-03 00:02 UTC, krisstern requested changes

2023-05-03 00:02 UTC, krisstern commented on README.md
> +Here is an example pipeline script that shows how to use the RegexBasedFilter feature in the gitlab trigger:
```suggestion
Here is an example pipeline script that shows how to use the RegexBasedFilter feature in the GitLab trigger:
```

2023-05-03 00:02 UTC, krisstern commented on README.md
> +    ?!: Indicates a negative lookahead assertion - find all that doesnt match.
```suggestion
    ?!: Indicates a negative lookahead assertion - find all that does not match.
```

2023-05-06 10:39 UTC, krisstern requested changes

2023-05-06 10:39 UTC, krisstern commented on README.md
> +```triggers {
````suggestion
```
triggers {
````

2023-05-06 10:39 UTC, krisstern commented on README.md
> +```triggers {
Formatting is a bit off here

2023-05-06 11:02 UTC, krisstern commented
Ready for a review?

2023-05-06 11:12 UTC, harsh-ps-2003 commented
> Ready for a review?

I'm sorry, did I mess up something? 😨

2023-05-06 11:16 UTC, krisstern commented
No, but you are suppoed to tell us when we should follow up with another review, say via a message or request to review button above on the top right panel.

2023-05-06 11:20 UTC, harsh-ps-2003 commented
Oh! I thought that I would be disturbing you guys. Yup! If it's good enough. Ready for review.

2023-05-06 11:31 UTC, krisstern requested changes

2023-05-06 11:31 UTC, krisstern commented on README.md
> +Keep in mind that the RegexBasedFilter feature is case-sensitive by default. If you want to make it case-insensitive, you can use the `(?i)` flag at the beginning of your regular expression pattern.
```suggestion
Keep in mind that the `RegexBasedFilter` feature is case-sensitive by default. If you want to make it case-insensitive, you can use the `(?i)` flag at the beginning of your regular expression pattern. For example: `^(?i)(?:(?!feature).)*$`.
```

2023-05-06 11:31 UTC, krisstern commented on README.md
> +Here is an example pipeline script that shows how to use the RegexBasedFilter feature in the GitLab trigger:
```suggestion
Here is an example pipeline script that shows how to use the `RegexBasedFilter` feature in the GitLab trigger:
```

2023-05-06 13:45 UTC, krisstern requested changes

2023-05-06 13:45 UTC, krisstern commented on README.md
> +    ?!: Indicates a negative lookahead assertion - find all that does not match.
```suggestion
    ?!: Indicates a negative lookahead assertion - finds all that does not match.
```

2023-05-06 13:45 UTC, krisstern commented on README.md
> +    .*: Matches any number of characters (except for newline) zero or more times.
```suggestion
    .*: Matches any number of characters (except for a newline) zero or more times.
```

2023-05-06 15:09 UTC, krisstern approved these changes

2023-05-06 15:09 UTC, merged

2023-05-06 15:09 UTC, krisstern commented
Thanks @harsh-ps-2003