Avoid caching the credential, instead get the credential value whenever it is required through the request filter
jenkinsci/gitlab-plugin pull request #1712
Opened 2024-10-22 04:20 UTC by arechavarria

### Description

This pull request introduces a new `GitlabCredentialResolver` class to manage the retrieval of credentials for GitLab connections more centrally and securely within the Jenkins GitLab plugin. The previous logic for handling API tokens has been refactored out of `GitLabConnection` and related classes into this new resolver class, improving code readability and maintainability.

Key changes include:
- Creation of the `GitlabCredentialResolver` class to handle credential resolution based on `Item` context and credential IDs.
- Refactoring `GitLabClientBuilder` and its implementations to accept a `GitlabCredentialResolver` instead of a plain API token string.
- Modifying `ApiHeaderTokenFilter` to utilize `GitlabCredentialResolver` for injecting API tokens into HTTP requests.
- Updates to unit tests to accommodate the new method of resolving credentials, ensuring compatibility with the new design.
- **Fix for AWS Secret Manager Issue**: Addressed an issue where, if AWS Secret Manager is used with a rotation mechanism, the plugin encounters problems because the client is cached and always uses the token with which it was initially created. This change ensures that credentials are retrieved each time they are used, allowing the plugin to work correctly with rotated tokens.

### Testing done

- **Unit Tests**: Updated existing tests to use `GitlabCredentialResolver`, ensuring they pass with the refactored code. This includes modifying tests like `AutodetectingGitLabClientTest` and `TestUtility`.
- **Manual Testing**: Verified the following scenarios manually:
  - Connection to GitLab using both global API tokens and job-specific credentials.
  - Ensured that the new `GitlabCredentialResolver` properly tracks credentials when associated with specific Jenkins items.
  - Verified that API requests include the correct `PRIVATE_TOKEN` header for both global and job-specific tokens.
  - Tested the resolution of credentials in environments with AWS Secret Manager to confirm that rotated tokens are correctly retrieved and used.
- **Automated Test Execution**: Ran all existing tests to ensure that there are no regressions introduced by this refactoring.

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2024-10-22 05:35 UTC, krisstern commented
https://github.com/jenkinsci/gitlab-plugin/pull/1711#issuecomment-2428185919:
> What's not clear? It turns out there is a related issue, when for example aws secret manager is used, there are credentials that are rotated, however the plugin caches the client and the same token is always used, which causes that when the credential rotates the plugin starts to generate errors with Gitlab, because it continues using the same token

2024-10-22 05:37 UTC, krisstern commented
Hi @arechavarria Thanks for the PR! But where is the item for the "Link to relevant issues in GitHub or Jira" you have indicated in the checklist that there is one?

2024-10-22 05:52 UTC, arechavarria commented
> Hi @arechavarria Thanks for the PR! But where is the item for the "Link to relevant issues in GitHub or Jira" you have indicated in the checklist that there is one? 

Hello, with pleasure 

I added the relationship with the issue: 
 https://github.com/jenkinsci/gitlab-plugin/issues/963

2024-10-22 06:23 UTC, krisstern commented
Hi @daniel-beck would it be able for you to take a look also and see if this PR would have any security issue(s) if merged as is?

2024-10-23 08:57 UTC, krisstern requested changes
I have a gut feeling we should be more careful about retricting any external use of the two methods concerned?

2024-10-23 08:57 UTC, krisstern commented on src/main/java/com/dabsquared/gitlabjenkins/connection/GitlabCredentialResolver.java
> +    public String getCredentialsId() {
```suggestion
    @Restricted(NoExternalUse.class)
    public String getCredentialsId() {
```

2024-10-23 08:57 UTC, krisstern commented on src/main/java/com/dabsquared/gitlabjenkins/connection/GitlabCredentialResolver.java
> +    public void setCredentialsId(String credentialsId) {
```suggestion
    @Restricted(NoExternalUse.class)
    public void setCredentialsId(String credentialsId) {
```

2024-10-23 16:33 UTC, krisstern requested changes

2024-10-23 16:33 UTC, krisstern commented on src/main/java/com/dabsquared/gitlabjenkins/connection/GitlabCredentialResolver.java
> +    public Item getItem() {
```suggestion
    @Restricted(NoExternalUse.class)
    public Item getItem() {
```

2024-10-23 16:33 UTC, krisstern commented on src/main/java/com/dabsquared/gitlabjenkins/connection/GitlabCredentialResolver.java
> +    public void setItem(Item item) {
```suggestion
    @Restricted(NoExternalUse.class)
    public void setItem(Item item) {
```

2024-10-23 16:33 UTC, krisstern commented on src/main/java/com/dabsquared/gitlabjenkins/connection/GitlabCredentialResolver.java
> +    public Item getItem() {
This is just to be safe, since its usage is wrapped around the already restricted `getApiToken` method in "GitLabClientBuilder.java".

2024-10-23 16:33 UTC, krisstern commented on src/main/java/com/dabsquared/gitlabjenkins/connection/GitlabCredentialResolver.java
> +    public void setItem(Item item) {
We may need this too because of its invocation in the unrestricted `getClient` method in "GitLabConnection.java".

2024-10-23 17:09 UTC, krisstern commented
Hi @arechavarria I will let this PR sit here for 24 to 48 hours. If there is no objection from the community within that time frame, I will proceed to merge it.

2024-10-23 17:09 UTC, krisstern approved these changes
LGTM

2024-10-23 17:26 UTC, arechavarria commented
Thanks @krisstern

2024-10-24 16:05 UTC, merged

2024-10-24 16:33 UTC, arechavarria commented
@krisstern I ask you at what point the release is managed so that the plugin is available in the marketplace?

2024-10-24 16:36 UTC, krisstern commented
Hi @arechavarria we have another PR #1713 pending to be merged soon. So we will need to wait until afterwards when a new release will be cut.