Feature add labels to env
jenkinsci/gitlab-plugin pull request #1713
Opened 2024-10-22 07:21 UTC by yiftahw

### Testing done

### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2024-10-23 07:51 UTC, krisstern requested changes

2024-10-23 07:51 UTC, krisstern commented on src/test/java/com/dabsquared/gitlabjenkins/environment/GitLabEnvironmentContributorTest.java
> +    public void testFreeStyleProjectLabels(CauseData data, String expected)
```suggestion
    public void testFreeStyleProjectLabels(CauseData causeData, String expected)
```

2024-10-23 07:51 UTC, krisstern commented on src/test/java/com/dabsquared/gitlabjenkins/environment/GitLabEnvironmentContributorTest.java
> +        GitLabWebHookCause cause = new GitLabWebHookCause(data);
```suggestion
        GitLabWebHookCause cause = new GitLabWebHookCause(causeData);
```

2024-10-23 11:11 UTC, krisstern requested changes
Hi @yiftahw, I think this implementation looks good but maybe we could add some instructions on how to use this feature before I can accept and merge this?

2024-10-23 11:12 UTC, krisstern commented
You can basically just copy and past what you have in the description to the README we have at the root

2024-10-23 12:52 UTC, yiftahw commented
> You can basically just copy and past what you have in the description to the README we have at the root

@krisstern thinking about what to put in the README, I thought to myself that people that will want to use this feature will probably suffer from some boilerplate of parsing the string held by the environment variable...  
I'm working now on adding a function called `GitLabMergeRequestLabelExists("some label") -> Boolean`
I'm kind of copying the mechanism used in `AcceptGitLabMergeRequestStep`
your thoughts?


example pipeline:
```groovy
script {
    if (GitLabMergeRequestLabelExists("bugfix"))
    {
        echo 'bugfix label detected!'
    }
}
```
instead of:  
```groovy
script {
    if (env.gitlabMergeRequestLabels) {
        def labels = env.gitlabMergeRequestLabels.split(',').collect { it.trim() }
        if ('bugfix' in labels) {
            echo 'bugfix label detected!'
        }
    }
}
```
I'm moving this to draft as I need to add some unit-tests but form initial testing with the docker setup it looks to be working fine

2024-10-23 16:39 UTC, krisstern commented
Hi @yiftahw, regarding:

> I'm working now on adding a function called GitLabMergeRequestLabelExists("some label") -> Boolean
I'm kind of copying the mechanism used in AcceptGitLabMergeRequestStep
your thoughts

Sounds like a reasonable approach to me! Please go ahead with the implementation.

2024-10-24 11:36 UTC, krisstern requested changes
Some more changes before we are good to go

2024-10-24 11:36 UTC, krisstern commented on src/test/java/com/dabsquared/gitlabjenkins/workflow/GitLabMergeRequestLabelExistsStepTest.java
> +    private void test_webhook_base(CauseData causeData, String expected)
```suggestion
    private void testWebhookBase(CauseData causeData, String expected)
```

2024-10-24 11:36 UTC, krisstern commented on src/test/java/com/dabsquared/gitlabjenkins/workflow/GitLabMergeRequestLabelExistsStepTest.java
> +    public void test_label_exists_in_mr_webhook()
```suggestion
    public void testLabelExistsInMrWebhook()
```

2024-10-24 11:36 UTC, krisstern commented on src/test/java/com/dabsquared/gitlabjenkins/workflow/GitLabMergeRequestLabelExistsStepTest.java
> +    public void test_no_labels_in_mr_webhook()
```suggestion
    public void testNoLabelsInMrWebhook()
```

2024-10-24 12:02 UTC, krisstern commented
Please apply `mvn spotless:apply` to fix the spotless issues

2024-10-24 12:29 UTC, krisstern approved these changes
LGTM

2024-10-24 12:30 UTC, krisstern commented
Hi @yiftahw the PR looks good now, thanks for your contribution! I will let it sit for between 24 and 48 hours before I merge it if there is no objection from the community.

2024-10-25 09:54 UTC, yiftahw commented
@krisstern before merging, I have some changes that close #1715 , they are pretty minor, should I push these changes here and you'll review them?

2024-10-25 15:09 UTC, krisstern commented
Hi @yiftahw I think it may be better to create another PR to address issue #1715. I can review that and merge it before cutting a new release.

2024-10-25 15:10 UTC, merged