added project_id to defined variables
jenkinsci/gitlab-plugin pull request #1722
Opened 2024-11-07 07:23 UTC by Aditya-PS-05

## closes #1693 

added project_id to defined variables

### Submitter checklist
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2024-11-07 07:44 UTC, krisstern commented
Hi @Aditya-PS-05, it looks like your proposed code changes introduced some unexpected test failures. You may want to check out the JUnit testing we have and see if any adjustment to our existing tests you will need to make.

2024-11-07 09:26 UTC, Aditya-PS-05 commented
@krisstern , try to test with mvn but it's showing errors in pom.xml. Should I create a new issue? Or only it's os specific in my ubuntu22.04 LTS

2024-11-07 09:42 UTC, krisstern commented
Hi @Aditya-PS-05, could you please share what errors you see regarding `pom.xml`? Without more info I cannot tell whether the issue is specific to your setup or not.

2024-11-07 09:57 UTC, krisstern commented
So I have just pulled your code and ran `mvn clean verify` with it. I don't see any issues with `pom.xml` though. What Java JDK version are you using?

2024-11-07 09:59 UTC, Aditya-PS-05 commented
When running `mvn clean install -X`

errors: 
```
[DEBUG] Writing tracking file /home/aditya/.m2/repository/io/jenkins/tools/bom/bom-weekly/3613.v584fca_12cf5c/_remote.repositories
[DEBUG] Writing tracking file /home/aditya/.m2/repository/io/jenkins/tools/bom/bom-weekly/3613.v584fca_12cf5c/bom-weekly-3613.v584fca_12cf5c.pom.lastUpdated
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unknown packaging: hpi @ org.jenkins-ci.plugins:gitlab-plugin:${revision}${changelist}, /home/aditya/my-work/open-source/gitlab-plugin/pom.xml, line 13, column 14
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Unknown packaging: hpi @ org.jenkins-ci.plugins:gitlab-plugin:${revision}${changelist}, /home/aditya/my-work/open-source/gitlab-plugin/pom.xml, line 13, column 14

    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:397)
    at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
    at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
    at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
    at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR]   
[ERROR]   The project org.jenkins-ci.plugins:gitlab-plugin:1.9.7-SNAPSHOT (/home/aditya/my-work/open-source/gitlab-plugin/pom.xml) has 1 error
[ERROR]     Unknown packaging: hpi @ org.jenkins-ci.plugins:gitlab-plugin:${revision}${changelist}, /home/aditya/my-work/open-source/gitlab-plugin/pom.xml, line 13, column 14
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

and when running `mvn test`

errors
```
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unknown packaging: hpi @ org.jenkins-ci.plugins:gitlab-plugin:${revision}${changelist}, /home/aditya/my-work/open-source/gitlab-plugin/pom.xml, line 13, column 14
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.jenkins-ci.plugins:gitlab-plugin:1.9.7-SNAPSHOT (/home/aditya/my-work/open-source/gitlab-plugin/pom.xml) has 1 error
[ERROR]     Unknown packaging: hpi @ org.jenkins-ci.plugins:gitlab-plugin:${revision}${changelist}, /home/aditya/my-work/open-source/gitlab-plugin/pom.xml, line 13, column 14
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

2024-11-07 10:03 UTC, krisstern commented
Regarding https://github.com/jenkinsci/gitlab-plugin/pull/1722#issuecomment-2461797075:

@Aditya-PS-05 Did you try to run `mvn clean verify`, and which version of Java JDK are you using?

2024-11-07 10:06 UTC, Aditya-PS-05 commented
> mvn clean verify

openjdk 21.0.5 2024-10-15 LTS

when running `mvn clean verify` 

res:
```
aditya@aditya-HP-Laptop-15s-du3xxx:~/my-work/open-source/gitlab-plugin$ mvn clean verify
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unknown packaging: hpi @ org.jenkins-ci.plugins:gitlab-plugin:${revision}${changelist}, /home/aditya/my-work/open-source/gitlab-plugin/pom.xml, line 13, column 14
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.jenkins-ci.plugins:gitlab-plugin:1.9.7-SNAPSHOT (/home/aditya/my-work/open-source/gitlab-plugin/pom.xml) has 1 error
[ERROR]     Unknown packaging: hpi @ org.jenkins-ci.plugins:gitlab-plugin:${revision}${changelist}, /home/aditya/my-work/open-source/gitlab-plugin/pom.xml, line 13, column 14
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
```

2024-11-07 10:08 UTC, krisstern commented
I have checked I don't think it is a `pom.xml` error, it is more like a local setup issue for you

2024-11-07 10:09 UTC, krisstern commented
And I am asking this for the 3rd time: Which Java JDK are you using?

2024-11-07 10:11 UTC, Aditya-PS-05 commented
> And I am asking this for the 3rd time: Which Java JDK are you using?

Sir, I already answered it 

it's OpenJDK 21.0.5 2024-10-15 LTS

2024-11-07 10:15 UTC, krisstern commented
My apologies you answered right after quoting `mvn clean verify` without any context so I could not tell you were specifying your Java version. Please be more careful in your replies moving forward. How about if you switch to Java 17 instead? What do you see?

2024-11-07 10:17 UTC, krisstern commented
And which Maven version are you currently using?

2024-11-07 11:21 UTC, Aditya-PS-05 commented
> And which Maven version are you currently using?

Apache Maven 3.6.3

2024-11-07 11:22 UTC, Aditya-PS-05 commented
> My apologies you answered right after quoting `mvn clean verify` without any context so I could not tell you were specifying your Java version. Please be more careful in your replies moving forward. How about if you switch to Java 17 instead? What do you see?

got it

2024-11-07 11:53 UTC, krisstern commented
@Aditya-PS-05 I think your Maven version is too old. The latest version is 3.9.x. So you may want to download the latest one say from here: https://maven.apache.org/download.cgi.

2024-11-08 07:29 UTC, krisstern requested changes

2024-11-08 07:29 UTC, krisstern commented on src/main/java/com/dabsquared/gitlabjenkins/cause/CauseData.java
> +        this.projectId = projectId == null ? 0 : projectId;
```suggestion
        this.projectId = Objects.requireNonNull(projectId, "projectId must not be null.");
```

We should not change the original logic for handling the `projectId` in "src/main/java/com/dabsquared/gitlabjenkins/cause/CauseData.java"

2024-11-11 13:48 UTC, closed without merging