Fix issue #506 : GitlabCommitStatus throws error after force kill
jenkinsci/gitlab-plugin pull request #548
Opened 2017-05-04 12:13 UTC by sbrassely

Fix CreationException when resuming inside script

2017-05-05 17:23 UTC, omehegan commented
@sbrassely thanks for this PR! We will review it ASAP.

2017-06-30 11:31 UTC, CSchulz commented on src/main/java/com/dabsquared/gitlabjenkins/workflow/AcceptGitLabMergeRequestStep.java
> -import com.dabsquared.gitlabjenkins.cause.GitLabWebHookCause;
You should not reorder all the imports.

2017-06-30 11:32 UTC, CSchulz commented on src/main/java/com/dabsquared/gitlabjenkins/workflow/AddGitLabMergeRequestCommentStep.java
> -import com.dabsquared.gitlabjenkins.cause.GitLabWebHookCause;
You should not reorder all the imports.

2017-06-30 11:32 UTC, CSchulz commented on src/main/java/com/dabsquared/gitlabjenkins/workflow/GitLabBuildsStep.java
> -import com.dabsquared.gitlabjenkins.gitlab.api.model.BuildState;
You should not reorder all the imports.

2017-06-30 11:32 UTC, CSchulz commented on src/main/java/com/dabsquared/gitlabjenkins/workflow/GitLabCommitStatusStep.java
> -import com.dabsquared.gitlabjenkins.gitlab.api.model.BuildState;
You should not reorder all the imports.

2017-06-30 11:32 UTC, CSchulz commented on src/main/java/com/dabsquared/gitlabjenkins/workflow/UpdateGitLabCommitStatusStep.java
> -import com.dabsquared.gitlabjenkins.gitlab.api.model.BuildState;
You should not reorder all the imports.

2017-06-30 11:32 UTC, CSchulz commented on src/main/java/com/dabsquared/gitlabjenkins/workflow/UpdateGitLabCommitStatusStep.java
> +		@Override
Wrong indentation.

2017-06-30 11:35 UTC, CSchulz requested changes

2017-06-30 11:35 UTC, CSchulz commented on src/main/java/com/dabsquared/gitlabjenkins/workflow/UpdateGitLabCommitStatusStep.java
> +		@Override
Wrong indentation.

2017-06-30 11:35 UTC, CSchulz commented on src/main/java/com/dabsquared/gitlabjenkins/workflow/AcceptGitLabMergeRequestStep.java
> -import com.dabsquared.gitlabjenkins.cause.GitLabWebHookCause;
You should not reorder all the imports.

2017-06-30 11:35 UTC, CSchulz commented on src/main/java/com/dabsquared/gitlabjenkins/workflow/AddGitLabMergeRequestCommentStep.java
> -import com.dabsquared.gitlabjenkins.cause.GitLabWebHookCause;
You should not reorder all the imports.

2017-06-30 11:35 UTC, CSchulz commented on src/main/java/com/dabsquared/gitlabjenkins/workflow/GitLabBuildsStep.java
> -import com.dabsquared.gitlabjenkins.gitlab.api.model.BuildState;
You should not reorder all the imports.

2017-06-30 11:35 UTC, CSchulz commented on src/main/java/com/dabsquared/gitlabjenkins/workflow/GitLabCommitStatusStep.java
> -import com.dabsquared.gitlabjenkins.gitlab.api.model.BuildState;
You should not reorder all the imports.

2017-06-30 11:35 UTC, CSchulz commented on src/main/java/com/dabsquared/gitlabjenkins/workflow/UpdateGitLabCommitStatusStep.java
> -import com.dabsquared.gitlabjenkins.gitlab.api.model.BuildState;
You should not reorder all the imports.

2017-06-30 11:35 UTC, CSchulz commented on src/main/java/com/dabsquared/gitlabjenkins/workflow/GitLabCommitStatusStep.java
> +		@Override
Wrong indentation.

2017-07-15 00:36 UTC, christ66 commented
👍 . I assume the import stuff happening is caused by your IDE grouping all import packages. Minor NIT, but I think still safe to merge.

2017-07-17 08:23 UTC, mreichel approved these changes

2017-07-17 17:47 UTC, merged

2017-09-05 08:39 UTC, Argelbargel commented
@omehegan: i think this got merged into the wrong branch. Should (also) go into master ;-)

2017-09-05 20:52 UTC, omehegan commented
@Argelbargel oh, weird. Wonder why this was submitted to that other branch. Eugh. At least I didn't mistakenly announce that this was released.

2017-09-05 21:06 UTC, omehegan commented
@sbrassely any chance you can resubmit this as a PR to master? If not I guess I can cherry pick these into master.

2017-09-06 07:38 UTC, sbrassely commented
@omehegan I create PR #622