Allow merge reqeusts to trigger multibranch builds.
jenkinsci/gitlab-plugin pull request #857
Opened 2018-11-23 05:52 UTC by omehegan

Fixes #416.

2018-11-23 05:58 UTC, omehegan commented
@pdudits if you have some time, could you review this? I was just feeling my way along a bit blindly here :)

2018-11-23 08:07 UTC, pdudits commented
Without a test case it's surely hard to tell the effect. Since this is entirely new branch of code, it might be safe to integrate. I have some proposal to cleaning that up, though, I'll post a review.

2018-11-26 02:48 UTC, omehegan commented
@pdudits thanks very much!

2018-11-26 08:21 UTC, pdudits requested changes

2018-11-26 08:21 UTC, pdudits commented on src/main/java/com/dabsquared/gitlabjenkins/webhook/build/SCMSourceOwnerNotifier.java
> +    public SCMSourceOwnerNotifier(Item project) {
The class only makes sense when given an SCMSourceOwner. At the call site this is already verified, so it's nicer to just allow these as projects

```suggestion
    public SCMSourceOwnerNotifier(SCMSourceOwner project) {
```

2018-11-26 08:21 UTC, pdudits commented on src/main/java/com/dabsquared/gitlabjenkins/webhook/build/SCMSourceOwnerNotifier.java
> +        for (SCMSource scmSource : ((SCMSourceOwner) project).getSCMSources()) {
Then you can remove any casts to SCMSourceOwner in the method

2018-11-26 08:21 UTC, pdudits commented on src/main/java/com/dabsquared/gitlabjenkins/webhook/build/SCMSourceOwnerNotifier.java
> +                    if (new URIish(gitSCMSource.getRemote()).equals(new URIish(gitSCMSource.getRemote()))) {
I read this as `if (a.equals(a))`. Both the constructor and getRemote() return the same thing. So the try block, and the if block can be removed.

2019-03-12 07:38 UTC, erenatas commented
Are there any specific reasons to why this MR is not being accepted?

2019-03-12 23:27 UTC, carloscaverobarca commented
+1 to accept this MR, currently I am using two separate job, one multibranch (created using DSL) and one normal pipeline for the MR, so the ideal solution for me would be to cover MR with the multibranch plugin.

2019-03-13 08:41 UTC, erenatas commented
> +1 to accept this MR, currently I am using two separate job, one multibranch (created using DSL) and one normal pipeline for the MR, so the ideal solution for me would be to cover MR with the multibranch plugin.

This will in the end create an unnecessary work... If it won't get merged that's what I will have to do also..
@carloscaverobarca if you have spare time, can you tell me how did you set a normal pipeline for merge requests? I have been trying to do it but builds does not trigger from gitlab. Push trigger starts the pipeline but merge request trigger does literally nothing. I would be very glad if you could help.

2019-03-14 10:39 UTC, carloscaverobarca commented
Sure. We used Gitflow workflow with develop and master branches. I defined a normal pipeline job with this configuration (same gitlab repository) including MR to master (see configuration in the second snapshot):

![build-configuration](https://user-images.githubusercontent.com/7501420/54350108-ea11ba80-464c-11e9-9504-b17cf4d60aa8.jpg)

![Pipeline](https://user-images.githubusercontent.com/7501420/54350141-fd248a80-464c-11e9-8506-b49beae85f34.jpg)

You also need to add a new MR webhook in GitLab to the jenkins job

![webhooks](https://user-images.githubusercontent.com/7501420/54350210-2513ee00-464d-11e9-9e8d-c3e7ffaf3300.jpg)

I realized just now, that it is possible to modify the jenkins jobs multibranch pipeline is generating, so probably it is not needed to add a new job, just only modify the one you need to Pipeline script from SCM:

![pipeline-configuration](https://user-images.githubusercontent.com/7501420/54350370-7c19c300-464d-11e9-9736-aa7827728d1a.jpg)

2019-03-14 12:28 UTC, erenatas commented
@carloscaverobarca Thank you so much for the reply! Unfortunately I don't have that option in a normal Pipeline job. I wonder if you have installed a plugin to get that option. I use Jenkins from stable image inside Docker. Maybe I should use latest?

2019-03-15 09:31 UTC, carloscaverobarca commented
@erenatas, I guess you need to install also the pipeline plugins, my installation is this one:
Jenkins 2.1.60
Gitlab plugin 1.5.11
Pipeline set of plugins:

![imagen](https://user-images.githubusercontent.com/7501420/54421742-5c49d400-470d-11e9-8ff7-e33409b413d1.png)

2019-03-15 16:23 UTC, erenatas commented
@carloscaverobarca you are the best! Thank you so much. I will try and let you know when I'm back at my laptop. Cheers!

2019-03-15 16:28 UTC, erenatas commented
@pdudits Are there any possibilities for reviewing and accepting this soon? Otherwise I will work on a workaround. Thanks!

2019-03-15 18:27 UTC, pdudits commented
@erenatas I am not the member if the repo, just helping out with the code reviews. So merging fully depends on time @omehegan is able to allocate for this.

What I can suggest though is:

* Try installing the merge request result from Jenkins: https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fgitlab-plugin/detail/multibranch-mr-support/5/artifacts. It would be very good if you can confirm whether this MR really fixes stuff for you.
* If you're familiar with maven and java, you can still build it yourself (also merged to master), it's just straightforward `mvn clean install`
* And if this plugin is important to you, and you have the capabilities and capacity to bring it forward, reach Owen, he'd appreciate some help.

2019-03-15 21:53 UTC, carloscaverobarca commented
@erenatas glad to help! @pdudits I will try to check whether it works and help @omehegan if I have time next week, the plugin is quite useful and cool.

2019-04-02 15:39 UTC, carloscaverobarca commented
@erenatas BTW found [this interesting blog](https://cinqict.github.io/post/eric/jenkinsdocker/) to install the plugins you need (even adapt your git repo) to generate your Jenkins developer docker image

2019-04-05 17:56 UTC, erenatas commented
> @erenatas BTW found [this interesting blog](https://cinqict.github.io/post/eric/jenkinsdocker/) to install the plugins you need (even adapt your git repo) to generate your Jenkins developer docker image

I haven't had the time to try the plugin yet due to the exams of my master's degree. Instead of doing it like this, I thought of getting backups of ```jenkins_home```. I created a jenkins volume and get ```tar``` of volume.

I need to build this plugin and try it on Monday. I will definitely let you know.

2019-05-22 13:04 UTC, MikeSafonov commented
Any plans to merge it?

2019-05-23 06:39 UTC, erenatas commented
Sorry I have forgotten to reply to this ticket. I couldn't make it work unfortunately.

2019-12-13 14:47 UTC, carloscaverobarca commented
Neither do I, I installed the version and Merge Requests are not launched. Currently I have no time to help with the source code. For the moment I am using the multibranch job and another pipeline job for the Merge Requests.

2023-05-06 14:02 UTC, closed without merging